[package]
name = "electronpy-tests"
version = "0.0.1"
edition = "2021"

[dev-dependencies]
electronpy-ast = { path = "../electronpy-ast" }
electronpy-parser = { path = "../electronpy-parser" }
electronpy-analysis = { path = "../electronpy-analysis" }
electronpy-optimizer = { path = "../electronpy-optimizer" }
electronpy-codegen-rust = { path = "../electronpy-codegen-rust" }
electronpy-ir = { path = "../electronpy-ir" }
electronpy-types = { path = "../electronpy-types" }

# Required so cargo doesn't complain about a lib-less package
[lib]
name = "electronpy_tests"
path = "src/lib.rs"
