[package]
name = "electronpy-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
electronpy-analysis = { path = "../electronpy-analysis" }
electronpy-codegen-rust = { path = "../electronpy-codegen-rust" }
electronpy-optimizer = { path = "../electronpy-optimizer" }
electronpy-parser = { path = "../electronpy-parser" }
