[package]
name = "electronpy-cli"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "electronpy"
path = "src/main.rs"

[dependencies]
anyhow = "1"
serde_json = "1"
rustpython-parser = "0.4"
electronpy-core = { path = "../electronpy-core" }
electronpy-ast = { path = "../electronpy-ast" }
electronpy-parser = { path = "../electronpy-parser" }
electronpy-ir = { path = "../electronpy-ir" }
electronpy-analysis = { path = "../electronpy-analysis" }
electronpy-optimizer = { path = "../electronpy-optimizer" }
electronpy-codegen-rust = { path = "../electronpy-codegen-rust" }
